# Generated by Django 4.2.4 on 2023-08-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="title")),
                ("content", models.TextField(blank=True, verbose_name="text")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="data"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="up_data"),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="photos/%Y/%m/%d", verbose_name="photo"
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
            ],
        ),
    ]
