# Generated by Django 4.2.4 on 2023-09-03 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_category_news_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="slug",
            field=models.SlugField(
                max_length=155, null=True, unique=True, verbose_name="URL"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="news.category",
                verbose_name="Категории",
            ),
        ),
    ]
