# Generated by Django 4.2.4 on 2023-09-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_remove_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                max_length=155, null=True, unique=True, verbose_name="URL"
            ),
        ),
    ]
